const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('skillMesh', {
  platform: process.platform,
  versions: {
    electron: process.versions.electron,
    chrome: process.versions.chrome,
    node: process.versions.node,
  },
  storage: {
    loadState: () => ipcRenderer.invoke('storage:loadState'),
    saveState: (state) => ipcRenderer.invoke('storage:saveState', state),
  },
  dialog: {
    openSkillPackage: () => ipcRenderer.invoke('dialog:openSkillPackage'),
    openPublishZip: () => ipcRenderer.invoke('dialog:openPublishZip'),
    openDirectory: (payload) => ipcRenderer.invoke('dialog:openDirectory', payload),
    confirm: (payload) => ipcRenderer.invoke('dialog:confirm', payload),
    restartPrompt: (payload) => ipcRenderer.invoke('dialog:restartPrompt', payload),
    skillConflict: (payload) => ipcRenderer.invoke('dialog:skillConflict', payload),
  },
  shell: {
    openPath: (targetPath) => ipcRenderer.invoke('shell:openPath', targetPath),
    openExternal: (targetUrl) => ipcRenderer.invoke('shell:openExternal', targetUrl),
    openSkillDir: (payload) => ipcRenderer.invoke('shell:openSkillDir', payload),
  },
  agents: {
    scan: () => ipcRenderer.invoke('agents:scan'),
    syncSkill: (payload) => ipcRenderer.invoke('agents:syncSkill', payload),
    validateSkillPath: (payload) => ipcRenderer.invoke('agents:validateSkillPath', payload),
  },
  skills: {
    ensurePackage: (skill) => ipcRenderer.invoke('skills:ensurePackage', skill),
    removePackage: (localPath) => ipcRenderer.invoke('skills:removePackage', localPath),
    verifyPackage: (payload) => ipcRenderer.invoke('skills:verifyPackage', payload),
    verifyPackages: (items) => ipcRenderer.invoke('skills:verifyPackages', items),
    packZip: (payload) => ipcRenderer.invoke('skills:packZip', payload),
    preparePublish: (payload) => ipcRenderer.invoke('skills:preparePublish', payload),
    finalizePublish: (payload) => ipcRenderer.invoke('skills:finalizePublish', payload),
    cleanupPublish: (payload) => ipcRenderer.invoke('skills:cleanupPublish', payload),
    readMarkdown: (payload) => ipcRenderer.invoke('skills:readMarkdown', payload),
    installToAgent: (payload) => ipcRenderer.invoke('skills:installToAgent', payload),
    uninstallFromAgent: (payload) => ipcRenderer.invoke('skills:uninstallFromAgent', payload),
    readPackageMeta: (payload) => ipcRenderer.invoke('skills:readPackageMeta', payload),
    listPackageTree: (payload) => ipcRenderer.invoke('skills:listPackageTree', payload),
    listAgentInstalled: () => ipcRenderer.invoke('skills:listAgentInstalled'),
    scanLocal: (payload) => ipcRenderer.invoke('skills:scanLocal', payload),
    getRegistry: () => ipcRenderer.invoke('skills:getRegistry'),
    resolveConflict: (payload) => ipcRenderer.invoke('skills:resolveConflict', payload),
  },
  sources: {
    testConnection: (payload) => ipcRenderer.invoke('sources:testConnection', payload),
    listSkills: (payload) => ipcRenderer.invoke('sources:listSkills', payload),
  },
  auth: {
    login: (payload) => ipcRenderer.invoke('auth:login', payload),
    logout: (payload) => ipcRenderer.invoke('auth:logout', payload),
    me: (payload) => ipcRenderer.invoke('auth:me', payload),
    myNamespaces: (payload) => ipcRenderer.invoke('auth:myNamespaces', payload),
  },
  hub: {
    publish: (payload) => ipcRenderer.invoke('hub:publish', payload),
    withdrawReview: (payload) => ipcRenderer.invoke('hub:withdrawReview', payload),
    deleteSkill: (payload) => ipcRenderer.invoke('hub:deleteSkill', payload),
    getSkillVersionStatus: (payload) => ipcRenderer.invoke('hub:getSkillVersionStatus', payload),
  },
  app: {
    relaunch: () => ipcRenderer.invoke('app:relaunch'),
    getPaths: () => ipcRenderer.invoke('app:getPaths'),
    setSkillsRoot: (payload) => ipcRenderer.invoke('app:setSkillsRoot', payload),
    getDiskSpace: (payload) => ipcRenderer.invoke('app:getDiskSpace', payload),
    getVersionInfo: () => ipcRenderer.invoke('app:getVersionInfo'),
    checkUpdate: (payload) => ipcRenderer.invoke('app:checkUpdate', payload),
    downloadUpdate: (payload) => ipcRenderer.invoke('app:downloadUpdate', payload),
    installUpdate: () => ipcRenderer.invoke('app:installUpdate'),
    rollbackUpdate: () => ipcRenderer.invoke('app:rollbackUpdate'),
    setUpdateFeedUrl: (payload) => ipcRenderer.invoke('app:setUpdateFeedUrl', payload),
    getPendingApplyStatus: () => ipcRenderer.invoke('app:getPendingApplyStatus'),
  },
  logs: {
    getInfo: () => ipcRenderer.invoke('logs:getInfo'),
    append: (payload) => ipcRenderer.invoke('logs:append', payload),
    purge: () => ipcRenderer.invoke('logs:purge'),
    openDir: () => ipcRenderer.invoke('logs:openDir'),
  },
  analytics: {
    getStats: (payload) => ipcRenderer.invoke('analytics:getStats', payload),
    getBulkStats: (payload) => ipcRenderer.invoke('analytics:getBulkStats', payload),
    recordView: (payload) => ipcRenderer.invoke('analytics:recordView', payload),
    favorite: (payload) => ipcRenderer.invoke('analytics:favorite', payload),
    unfavorite: (payload) => ipcRenderer.invoke('analytics:unfavorite', payload),
    recordDownload: (payload) => ipcRenderer.invoke('analytics:recordDownload', payload),
    recordInstall: (payload) => ipcRenderer.invoke('analytics:recordInstall', payload),
    recordUsage: (payload) => ipcRenderer.invoke('analytics:recordUsage', payload),
    listPending: () => ipcRenderer.invoke('analytics:listPending'),
    clearPending: (payload) => ipcRenderer.invoke('analytics:clearPending', payload),
  },
  skillIndex: {
    getMeta: () => ipcRenderer.invoke('skillIndex:getMeta'),
    readAll: () => ipcRenderer.invoke('skillIndex:readAll'),
    replaceAll: (payload) => ipcRenderer.invoke('skillIndex:replaceAll', payload),
    search: (payload) => ipcRenderer.invoke('skillIndex:search', payload),
  },
})
